#!/bin/bash

#############################################################
#   This script is used by McM when it performs automatic   #
#  validation in HTCondor or submits requests to computing  #
#                                                           #
#      !!! THIS FILE IS NOT MEANT TO BE RUN BY YOU !!!      #
# If you want to run validation script yourself you need to #
#     get a "Get test" script which can be retrieved by     #
#  clicking a button next to one you just clicked. It will  #
# say "Get test command" when you hover your mouse over it  #
#      If you try to run this, you will have a bad time     #
#############################################################

cd /afs/cern.ch/cms/PPD/PdmV/work/McM/submit/TSG-Phase2HLTTDRWinter20DIGI-00281/

# Make voms proxy
voms-proxy-init --voms cms --out $(pwd)/voms_proxy.txt --hours 4
export X509_USER_PROXY=$(pwd)/voms_proxy.txt

export SCRAM_ARCH=slc7_amd64_gcc820

source /cvmfs/cms.cern.ch/cmsset_default.sh
if [ -r CMSSW_11_0_2/src ] ; then
  echo release CMSSW_11_0_2 already exists
else
  scram p CMSSW CMSSW_11_0_2
fi
cd CMSSW_11_0_2/src
eval `scram runtime -sh`

scram b
cd ../..

# Maximum validation duration: 28800s
# Margin for validation duration: 30%
# Validation duration with margin: 28800 * (1 - 0.30) = 20160s
# Time per event for each sequence: 50.0000s
# Threads for each sequence: 8
# Time per event for single thread for each sequence: 8 * 50.0000s = 400.0000s
# Which adds up to 400.0000s per event
# Single core events that fit in validation duration: 20160s / 400.0000s = 50
# Produced events limit in McM is 10000
# According to 1.0000 efficiency, validation should run 10000 / 1.0000 = 10000 events to reach the limit of 10000
# Take the minimum of 50 and 10000, but more than 0 -> 50
# It is estimated that this validation will produce: 50 * 1.0000 = 50 events
EVENTS=50


# cmsDriver command
cmsDriver.py  --python_filename TSG-Phase2HLTTDRWinter20DIGI-00281_1_cfg.py --eventcontent FEVTDEBUGHLT --pileup 'AVE_200_BX_25ns,{"B":(-3,3)}' --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM-DIGI-RAW --fileout file:TSG-Phase2HLTTDRWinter20DIGI-00281.root --pileup_input "dbs:/MinBias_TuneCP5_14TeV-pythia8/Phase2HLTTDRWinter20GS-110X_mcRun4_realistic_v3-v1/GEN-SIM" --conditions 110X_mcRun4_realistic_v3 --step DIGI:pdigi_valid,L1,L1TrackTrigger,DIGI2RAW,HLT:@fake2 --geometry Extended2026D49 --filein file:TSG-Phase2HLTTDRWinter20GS-00252.root --era Phase2C9 --no_exec --mc -n $EVENTS || exit $? ;
